services:
  web:
    networks:
      - parsers
    container_name: study-cats
    build: ./cats
    command: gunicorn cats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./cats/static:/home/project/static
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - ./cats/static:/home/project/static
    expose:
      - 80
    depends_on:
      - web
    networks:
      - parsers
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.study-http-router.entrypoints=websecure"
      - "traefik.http.routers.study-http-router.rule=Host(`study.ada-lave.ru`)"
      - "traefik.http.routers.study-http-router.tls=true"
      - "traefik.http.routers.study-http-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.study-http-router.service=study-http-service"
      - "traefik.http.services.study-http-service.loadbalancer.server.port=80"

networks:
  parsers:
    name: parsers
    external: true
