# Generated by Django 5.1.5 on 2025-01-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_adoption_options_alter_cat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.cat', verbose_name='Кот'),
        ),
    ]
